plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
}

android {
    namespace 'com.viaplay.test'

    compileSdk 36

    defaultConfig {
        applicationId "com.viaplay.test"
        minSdkVersion 24
        targetSdkVersion 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.5.14'
    }
}

dependencies {
    implementation(project(":core:data"))
    implementation implementation(project(':feature:feature-dashboard'))
    implementation(project(":feature:feature-details"))

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.compose.material
    implementation libs.androidx.navigation3.runtime
    implementation libs.androidx.navigation3.ui
    implementation libs.androidx.lifecycle.viewmodel.navigation3

    implementation libs.hilt
    implementation libs.hilt.navigation.compose
    ksp libs.hilt.compiler
    ksp libs.androidx.room.compiler

    implementation libs.gson

    testImplementation libs.junit
}